"""
Django settings for core project (Lumen backend).

Generated by 'django-admin startproject' using Django 5.2.2.
Documentation:
- General: https://docs.djangoproject.com/en/5.2/topics/settings/
- Full ref: https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# ==============================================================================
# 📁 BASE CONFIGURATION
# ==============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = "django-insecure-dcab)t9v)_9-6md_yd#738ndyi)cq*xm+hx5x$4rj*n326*+@d"
DEBUG = True
ALLOWED_HOSTS = []

# ==============================================================================
# 🧩 APPLICATIONS
# ==============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# ==============================================================================
# ⚙️ MIDDLEWARE
# ==============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ==============================================================================
# 🌐 URL & WSGI
# ==============================================================================

ROOT_URLCONF = "core.urls"
WSGI_APPLICATION = "core.wsgi.application"

# ==============================================================================
# 🗃️ DATABASE
# ==============================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ==============================================================================
# 🔐 AUTHENTICATION
# ==============================================================================

# External Auth API endpoint (used for validating JWTs)
AUTH_API_URL = "https://ant-django-auth-62cf01255868.herokuapp.com/api"

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "gait_integration.authentication.ExternalJWTAuthentication",
    ]
}

# ==============================================================================
# 🔐 PASSWORD VALIDATION
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ==============================================================================
# 🌍 INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/New_York"
USE_I18N = True
USE_TZ = True

# ==============================================================================
# 📦 STATIC FILES
# ==============================================================================

STATIC_URL = "static/"

# ==============================================================================
# 🆔 PRIMARY KEY CONFIG
# ==============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
